# docker compose -f example.yml -p example up -d
# docker compose -f example.yml -p example down --volumes

### This example shows how to switch to another non-root user
### and how to set the VNC password (to an empty one) and VNC resolution.

version: '3'

services:
  test:
    image: accetto/ubuntu-vnc-xfce-g3:extended
    # environment:
    #   - VNC_PW=
    #   - VNC_RESOLUTION=1024x768
    ports:
      - ":5901"
      - ":6901"
    user: "2000:3000"
